project:
  type: book

filters:
  - r-wasm/live

book:
  title: "Python pentru Începatori"
  author: "Robert Zofei"
  date: "5/3/2026"
  chapters:
    - index.qmd
    - chapters/ifElse.qmd
    - chapters/whileFor.qmd
    - chapters/functii.qmd
    - chapters/liste.qmd
    - chapters/dictionare.qmd
    - chapters/references.qmd

bibliography: chapters/references.bib

format:
  html:
    theme:
      light: cosmo
      dark: darkly

    # respect-user-color-scheme: true

  pdf:
    documentclass: scrreprt
