---
title: Functii
jupyter: python3
---

***

Am folosit pana acum functiile `print()`, `len()`, `input()` si multe altele. Aceste functii sunt deja incluse in Python, dar stiati ca putem sa ne scriem propriile noastre functii?

### La ce ne ajuta functiile?

Functiile sunt ca niste mini programe in interiorul programului nostru principal. Ne ajuta la:

- **Reutilizare**: Scriem codul o singura data si il apelam de cate ori avem nevoie. Nu rescriem acelasi cod iar si iar. Astfel evitam sa ne repetam.
- **Organizare**: Impartim un program mare in functii mici.
- Obtinerea unui **cod lizibil**: O functie cu un nume sugestiv ii spune instant cititorului ce face codul, fara a fi nevoit sa desluseasca ce au scris altii inaintea lui.
- O **mentenanta mai usoara**: Daca trebuie sa reparam sau sa schimbam ceva, facem modificarea intr-un singur loc, nu in zece.

***

Ce vom invata in acest capitol:

- la ce ne ajuta functiile;
- cum scriem o functie folosind instructiunile `def` si `return`;
- valoarea `none`;
- variabile locale si variabile globale.


## Instructiunea def

### Cu ce cuvant se creeaza o functie?

```{python}
# Calculam media lui Mihai.
note_mihai = [6, 5, 4]
total1 = sum(note_mihai)
media1 = total1 / len(note_mihai)
print(media1) # media1 = 5.0

# -----------------------------------------
# Calculam media lui Andrei.
note_andrei = [8, 10, 9]
total2 = sum(note_andrei)
media2 = total2 / len(note_andrei)
print(media2) # media2 = 9.0

```

O functie se creeaza folosind cuvantul cheie `def`.

```{python}
def calculeaza_media(note):
    total = sum(note)
    return total / len(note)

note_mihai = [6, 5, 4]
note_andrei = [8, 10, 9]

print(calculeaza_media(note_mihai))  # 5.0
print(calculeaza_media(note_andrei))  # 9.0
``` 

***

## Instructiunea return

```{python}
def suma2(a,b)
    return a+b

print(suma2(3,7))
```

### Ce este o valoare returnata? Poate sa faca parte dintr-o expresie?



## Valoarea None


### Ce tip de date este valoare None?
What is the data type of None?

## Variabile locale si variabile globale

```{python}
def ultima_cifra(nr):
    return
```

1. How can you force a variable in a function to refer to the global variable?


## Intrebari

- [X] La ce ne ajuta functiile?

- [X] Cu ce cuvant se creeaza o functie?

- [ ] Cand se executa codul dintr-o functie -- cand functia este definita, sau atunci cand functia este apelata?
  
- [ ] Care e diferenta dintre o functie si apelul unei functii?

- [ ] Câte domenii de vizibilitate globale (global scopes) există într-un program Python? Dar domenii de vizibilitate locale (local scopes)?
  
- [ ] Ce se întâmplă cu variabilele dintr-un domeniu local după ce apelul funcției se încheie?
  
- [ ] Ce este o valoare returnată (return value)? Poate o valoare returnată să facă parte dintr-o expresie?

- [ ] Dacă o funcție nu conține o instrucțiune return, care va fi valoarea returnată în urma apelării acelei funcții?

- [ ] Cum poți forța o variabilă din interiorul unei funcții să facă referire la o variabilă globală?

- [ ] Care este tipul de date al valorii None?

- [ ] Ce face instrucțiunea import areallyourpetsnamederic?

- [ ] Dacă ai avea o funcție numită bacon() într-un modul numit spam, cum ai apela-o după importarea modulului spam?

- [ ] Cum poți preveni întreruperea bruscă (crash-ul) a unui program atunci când apare o eroare?

- [ ] Ce fel de cod se include în blocul try? Dar în blocul except?