---
title: Structuri de decizie
jupyter: python3
---

Astazi vom invata calculatorul sa ia decizii singur. Pentru a putea face asta, avem nevoie sa intelegem trei concepte: tipul de date Boolean, operatorii de comparatie, si instructiunile if/ else.

## Tipul de date Boolean
In tipurile de date cu care am lucrat pana acum, adica cele pentru numere si siruri de caractere, puteam sa memoram aproape orice numar sau text pe care ni le doream. Ei bine, variabilele de tip Boolean pot stoca doar doua valori: True sau False, adica adevarat sau fals. Doua lucruri importante: valorile acestea nu apar scrise intre ghilimele (cum erau string-urile), si incep mereu cu litera mare.

```{python}
a =  "text"
b = True
print(type(a))
print(type(b))
```

Asta inseamna ca variabila **a** este de tip string, iar variabila **b** este de tip Boolean.

```{python}
a = True
b = False
print(a,b)
```

Poate ca va intrebati de unde vine aceasta denumire de Boolean. Acest tip de date este numit dupa matematicianul britanic George Boole. El a inventat algebra logica si a pus bazele functionarii tuturor calculatoarelor si a limbajelor de programare pe care le folosim noi astazi.

## Operatorii de Comparatie (==,  !=,  <,  >)

De multe ori, o decizie implica comparatia dintre doua sau mai multe valori. Pentru asta, avem niste operatori speciali:

| Operator | Ce înseamnă |
| :--- | :--- |
| `==` | Egal cu |
| `!=` | Nu e egal cu |
| `<` | Mai mic decât |
| `>` | Mai mare decât |
| `<=` | Mai mic sau egal cu |
| `>=` | Mai mare sau egal cu |

Haide sa incepem prin a compara niste numere intre ele (rezultatul va aparea sub bucata de cod):

```{python}
1 == 1
```

```{python}
4 == 32
```

```{python}
2 != 3
```

```{python}
2 != 2
```

```{python}
64 == 64.0
```

---
Putem compara si bucati de text:

```{python}
'salut' == 'salut'
```

```{python}
'salut' == 'Salut'
```

---

Pana ca si valorile de adevar pot fi comparate intre ele:

```{python}
True == True
```

```{python}
True != False
```

```{pyodide}
a = 1
print(a)
```

### Diferenta dintre operatorul = si operatorul ==

Acesti doi operatori sunt usor de confundat, iata ce trebuie sa retineti ca sa nu-i incurcati:

- Operatorul = pune valoarea din dreapta in variabila din stanga
- Operatorul == (egal cu) verifica daca doua valori sunt egale

Exemplu:

```{python}
a = 2 
print(a == 2) # verifica daca valoarea din variabila 'a' este egala cu 2
```

## Operatori Booleeni (and, or, not)
Avem, de asemenea, la dispozitia noastra si operatorii, **and**, **or**, si respectiv, **not**.

Operatorul **and** verifica daca absolut toate expresiile comparate sunt adevarate.
```{python}
(1 < 5) and (2 < 5)
```

```{python}
(1 < 5) and (2 < 5) and (10 < 5)
```

Vedem ca e de ajuns ca o singura expresie sa fie falsa ca rezultatul sa fie fals.


Operatorul **or** verifica daca cel putin una dintre expresii este adevarata.
```{python}
(1 == 2) or (2 == 2)
```

Operatorul **not** neaga valoarea de adevar. Spre deosebire de **and** si **or**, **not** opereaza pe o singura expresie. Pur si simplu returneaza valoarea opusa.

```{python}
not True
```


## If/ Else

Vrem sa se execute o bucata de cod daca si nu mai daca se indeplineste o conditie, dar cum putem sa facem asta? Pai, cu ajutorul structurilor de decizie **(if, else, elif)**:

### Instructiunea if

Sa zicem ca avem un program care verifica daca numele cuiva este "Alin". Ne prefacem ca cineva a introdus mai devreme o valoare in variabila *nume*.

```{python}
nume = "Alin"
if nume == "Alin":
    print("Salut, Alin!")
```

In limbaj natural, am citi liniile de cod de mai sus astfel:

- In variabila **nume** se memoreaza textul "Alin"
- Daca valoarea din variabila **nume** este aceeasi sau este egala cu textul "Alin", atunci se afiseaza pe ecran mesajul "Salut, Alin!"

Daca expresia urmata de if este adevarata, sau, cu alte cuvinte, conditia a fost indeplinita, atunci toate liniile de cod ce scrise cu alineat imediat sub instructiunea if se vor executa.  Acest alineat, in lumea programarii, se numeste indentare, si se obtine apasand tasta **tab**. Daca expresia se evalueaza ca fiind falsa, insa, atunci calculatorul ignora liniile de cod indentate aflate imediat sub if.

Instructiunea **if** contine:

1. Cuvantul cheie **if**
2. O conditie (adica o expresie care se evalueaza ca fiind True sau False)
3. Doua puncte **:**
4. Incepand cu linia urmatoare, un bloc indentat de cod (numit si clauza if)


### Instructiunea else

Sa zicem ca avem un site si vrem sa verificam daca un utilizator si-a introdus parola corecta.

```{python}
parola = "xyz"

if parola == "xyz": 
    print("Acces permis.") 
else: 
    print("Ati introdus parola gresita.")
```

In limbaj natural, am citi aceste linii de cod astfel: 

- Parola introdusa de utilizator este **xyz**. 
- Daca parola este **xyz**, atunci se afiseaza pe ecran mesajul "Acces permis". 
- Altfel, se afiseaza mesajul "Ati introdus parola gresita."

Instructiunea **else** contine:

1. Cuvantul cheie **else**
2. Doua puncte **:**
3. Incepand cu linia urmatoare, un bloc indentat de cod (numit si clauza else)

### Instructiunea elif

Ar putea exista situatia in care trebuie sa verificam mai multe cazuri. In aceasta situatie folosim instructiunea **elif**, care inseamna **else if**. Aceasta instructiune poate fi folosita doar daca urmeaza dupa o instructiune **if** sau o alta instructiune **elif**.

Sa luam un exemplu in care verificam varsta cuiva:

```{python}
varsta = 1520 # de ani

if varsta < 18:
    print("Esti copil.")
elif varsta > 1000:
    print("🧛 Esti vampir.")
elif varsta > 18:
    print("Esti adult.")
```

Observati ca ordinea instructiunilor **elif** din acest exemplu este una avantajoasa. Daca inversam cele doua **elif**-uri, programul ar fi putut oferi raspunsuri gresite cand valoarea varstei depasea 1000. Ar fi spus ca o persoana de 1001 de ani este adult. Asta se intampla pentru ca expresiile se evalueaza pe rand de sus in jos. Odata ce una este corecta, se executa codul din clauza instructiunii respective, iar restul nu se mai verifica. De asemenea, bineinteles ca nu exista persoane de 1000 de ani sau vampiri (mai stii?).

```{python}
# Varianta gresita
varsta = 1001 # de ani

if varsta < 18:
    print("Esti copil.")
elif varsta > 18:
    print("Esti adult.")
elif varsta > 1000:
    print("🧛 Esti vampir.")
```

Instructiunea **elif** contine:

1. Cuvantul cheie **elif**
2. O conditie (care se evalueaza cu True sau False)
3. Doua puncte **:**
4. Incepand cu linia urmatoare, un bloc indentat de cod (numit si clauza elif)