---
title: Structuri repetitive
jupyter: python3
format:
  html:
    code-line-numars: true
---

***

Pana acum am invatat cum sa scriem programe formate din linii de cod care se executa, de sus in jos, o singura data. Dar in majoritatea programelor utile avem nevoie sa repetam instructiuni. Acest fapt ne permite sa automatizam lucrurile repetitive sau plictisitoare pe care le avem de facut. De exemplu: sa verificam fiecare obiect dintr-o lista, sa-i cerem unui utilizator sa introduca niste date pana cand o face in mod corect, sau sa facem un joc sa mearga pana cand jucatorul pierde.

In acest capitol vom invata urmatoarele concepte:

- Bucla `while` -- repeta un bloc de cod cat timp conditia este adevarata (True).
- Instructiunea `break` -- opreste executia unei bucle inainte de indeplinirea conditiei.
- Instructiunea `continue` -- trece peste restul iteratiei curente si sare la urmatoarea.
- Bucla `for` -- repeta un bloc de cod de un numar specific de ori, sau pentru fiecare obiect dintr-o lista.
- Functia `range()` -- genereaza o secventa de numere. De obicei se foloseste pentru a se specifica de cate ori se repeta o bucla `for`.

***

Salutare dragii mei, eu sunt Robi, iar astazi vom invata cum functioneaza instructiunile `while` si `break` in Python.

## Bucle while

Buclele `while`, (in engleza while loops) permit executarea in mod repetat a unei secvente de linii de cod cat timp se respecta o anumita conditie.

Incepem cu buclele `while`. Haide sa ne uitam la aceste doua bucati de cod. 

```{python}
numar = 0
if numar < 3:
    print(numar)
    numar += 1
```

```{python}
numar = 0
while numar < 3:
    print(numar)
    numar += 1
```

***

Nu dureaza mult sa observam ca arata aproape identic: singura diferenta dintre ele este ca in primul avem instructiunea `if`, iar in celalalt avem instructiunea `while`.



Avem variabila `numar` in care memoram valoarea 0. Apoi urmeaza conditia: daca, `numar` este strict mai mic decat 3, atunci se afiseaza pe ecran numarul si ii crestem valoarea acestuia cu 1, adica din 0 devine 0 + 1 = 1. In continuare, insa,  apare diferenta:

- Daca conditia este respectata, clauza `if` (adica blocul de cod indentat aflat imediat sub instructiunea `if`) se executa o singura data .

- Codul din clauza `while` va continua sa se execute cat timp conditia este adevarata (True), mai exact cat timp `numar` este strict mai mic decat 3.

***

Iata un program enervant, dar care ne ajuta sa intelegem mai bine cum functioneaza buclele `while`. 

```{python}
#| eval: false
nume = ""
while nume != "cum te cheama":
    print("Te rog scrie cum te cheama")
    nume = input()
print("Mersi!")
```


```
Te rog scrie cum te cheama
Rob
Te rog scrie cum te cheama
Robert
Te rog scrie cum te cheama
???????
Te rog scrie cum te cheama
cum te cheama
Mersi!
```

***

Observam in prima linie de cod `1` ca memoram un string gol in variabila `nume`. Sa ai un string gol e ca si cum ai deschide un proiect nou in Word si inca n-ai apucat sa scrii nimic. Stii doar ca urmeaza sa fie cuvinte acolo. La fel este si aceasta variabila -- calculatorul stie ca este de tip String, dar nu contine nimic.

***

Instructiunea `while` este compusa din:

1. Cuvantul cheie `while`
2. O conditie (adica o expresie care se evalueaza ca True sau False)
3. Doua puncte `:`
4. Incepand cu linia urmatoare, un bloc indentat de cod (numit si clauza while)

***

Forma 1:

```{python}
lista = [64, 32, 4, 1, 0, -8, 100]
i = 0

while lista[i] > 0:
    print(f"Numar valid: {lista[i]}")
    i += 1

print("Bucla while s-a oprit pentru ca"
      " am intalnit o valoare <= 0")
```

### Bucla infinita (Infinite Loop)

Forma 2:

```{python}
#| eval: false
while True:
    print("Salutare fratilor!")
```

## Instructiunea break

Forma 3:


Exista o scurtatura care face ca bucla sa se opreasca din executie mai devreme, iar aceasta se numeste `break`. Atunci cand executia ajunge la instructiunea `break`, programul iese imediat din bucla respectiva. 

**Atentie!** Se opreste doar bucla, nu si restul programului.

```{python}
numar = 0
print("Incepe numaratoarea")
while numar < 11:
    if numar == 4:
        break
    numar += 1
    print(numar)
print("Numaratoarea s-a incheiat")
```

***

Iarasi avem un program care numara. Ar trebui sa numere de la 1 la 10 dar observam acel `if` de la linia `4` care se executa sa verifice daca numarul este egal cu 4. Daca conditia este True, se executa instructiunea `break`, iar bucla `while` se opreste. La final, se trece mai departe la ultima linie de cod `8`. Altfel, se trece peste clauza `if` si executia sare inapoi la inceputul buclei `while` pentru a verifica din nou conditia `numar < 11`.

Acest program ar fi trebuit sa numere de la 1 pana la 10. Dar vedem ca este impusa conditia ca programul sa se opreasca daca numarul este egal cu 4.

***

```{python}
lista = [16, 4, 1, 0, -2, -4, 100]
suma = 0
i = 0

while True:
    suma += lista[i]
    i += 1
    if lista[i] == 0:
        break

print(suma)
```

***

Un script de login care ne cere parola cat timp aceasta este gresita.

```{python}
#| eval: false
PAROLA_CORECTA = "Andrei_123"

while True:
    parola_introdusa = input("Introdu parola:")

    if parola_introdusa == PAROLA_CORECTA:
        print("Acces permis!")
        break
    else:
        print("Parola incorecta!")

print("Programul continua...")
```

Introdu parola:jony

Parola incorecta!

Introdu parola:23

Parola incorecta!

Introdu parola:Andrei_123

Acces permis!

Programul continua...

***

while True creeaza din start o bucla infinita controlata. Programul porneste executia buclei fara sa verifice nicio conditie prealabila.

***



## Instructiunea continue

Instructiunile `continue`, asemenea celor `break`, sunt folosite in interiorul buclelor. Cand executia unui program ajunge la o instructiune `continue`, aceasta se intoarce inapoi la inceputul buclei si evalueaza din nou conditia.

```{python}
for numar in range(10):
    if numar % 2 == 0:
        continue
    print(numar)
```

```{python}
facturi = [150.5, 0, 1200.75]
total_incasari = 0

for factura in facturi:
    if factura == 0:
        print("Factura anulata (0 RON). Dam skip.")
        continue

    print(f"Procesez plata pentru: {factura} RON")
    total_incasari += factura

print(f"Total procesat: {total_incasari} RON")
```

***

## Bucle for
```{python}
lista = ["Michael Jackson", "Selly", "Maria"]
for membru in lista:
    print(membru)
```

Afiseaza pe ecran fiecare membru din lista, cate unul la fiecare iteratie.

```{python}
numere = [27, 7, 4, 32]
for numar in numere:
    print(numar)
```

```{python}
numere = [27, 7, 4, 32]
total = 0
for numar in numere:
    print(numar)
    total = total + numar
print(f"Total = {total}")
```


```{python}
cnp_cautat = "1900512123456"
baza_date_clienti = ["1890101001122", 
                     "7910303445566", 
                     "1900512123456", 
                     "5010202998877"]

for cnp in baza_date_clienti:
    print(f"Scanez: {cnp}")
    
    if cnp == cnp_cautat:
        print("Client găsit! Opresc scanarea bazei de date.")
        break

print("Se executa restul programului...")
```

***

## Functia range()

Vrem sa cream o lista cu numerele 1, 2, 3, 4.

```{python}
# lista = [1,2,3,4]
lista = list(range(1,5))
print(lista)
```


## Match case (Switch case)

`match` `case` este echivalentul lui `switch` `case` din `C++` sau alte limbaje de programare.

```{python}
value = 2
match value:
    case 1:
        result = "one"
    case 2:
        result = "two"
    case 3:
        result = "three"
    case _:
        result = "unknown"
print(result)
```

## Leftovers



## Titlu

While si Break in Python (Tutorial Python Pentru Incepatori Ep. 6)